config/routes.rb
Rails.application.routes.draw do
  resources :adverts
  root 'main#index'
  get '/:action(/:id)', controller: 'main'
end

app/models/advert.rb
class Advert < ActiveRecord::Base
  belongs_to :company

  def to_jbuilder
    Jbuilder.new do |json|
      company = Company.find(self[:company_id])

      json.(self, :id, :filename, :company_id)
      json.title company[:name]
      json.text company[:preview_text]
      json.small small_version(self[:filename])
    end
  end

  def as_json
    to_jbuilder.attributes!
  end

  def small_version(filename)
    filename.gsub(/(.+)\.(.+)$/, '\1_small.\2')
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  include PgSearch

  has_many :images
  has_many :adverts
  has_and_belongs_to_many :tags

  pg_search_scope :search_by_name,
    :against => {
      :name => 'A'
    },
    :using => {
      :tsearch => {
        :prefix => true
      },
      :trigram => {
        :threshold => 0.15
      }
    },
    :order_within_rank => "companies.name DESC"
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :company
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :tag_category
  has_and_belongs_to_many :companies
end

app/models/tag_category.rb
class TagCategory < ActiveRecord::Base
  has_many :tags
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  before_action :set_advert, only: [:show, :edit, :update, :destroy]

  # GET /adverts
  # GET /adverts.json
  def index
    @adverts = Advert.all
  end

  # GET /adverts/1
  # GET /adverts/1.json
  def show
  end

  # GET /adverts/new
  def new
    @advert = Advert.new
  end

  # GET /adverts/1/edit
  def edit
  end

  # POST /adverts
  # POST /adverts.json
  def create
    @advert = Advert.new(advert_params)

    respond_to do |format|
      if @advert.save
        format.html { redirect_to adverts_path, notice: 'Advert was successfully created.' }
        format.json { render :show, status: :created, location: @advert }
      else
        format.html { render :new }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adverts/1
  # PATCH/PUT /adverts/1.json
  def update
    respond_to do |format|
      if @advert.update(advert_params)
        format.html { redirect_to @advert, notice: 'Advert was successfully updated.' }
        format.json { render :show, status: :ok, location: @advert }
      else
        format.html { render :edit }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adverts/1
  # DELETE /adverts/1.json
  def destroy
    @advert.destroy
    respond_to do |format|
      format.html { redirect_to adverts_url, notice: 'Advert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advert
      @advert = Advert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advert_params
      params.require(:advert).permit(:filename, :company_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
require File.join(Rails.root, 'lib/remoteimage')

class MainController < ApplicationController
  def index
  end

  def search
    if (query = params[:id])
      company = JSON[Company.search_by_name(query).select('id, name, logo').limit(15).to_json]
    else
      company = JSON[Company.all.select('id, name, logo').order('name').to_json]
    end

    company.each do |item|
      if item['logo']
        item['logo'].gsub! 'http://www.artplay.ru', '.'
        item['logo'] = nil unless exists(item['logo'])
      end
    end if !!ENV['INTERNAL_ASSETS']

    company = JSON.pretty_generate(company) if params.has_key? :pretty

    render json: company
  end

  def building
    building = JSON[Company
      .where("location LIKE :prefix", prefix: "#{params[:id]}-%")
      .select('id, name, logo').to_json]

    building.each do |item|
      if item['logo']
        item['logo'].gsub! 'http://www.artplay.ru', '.'
        item['logo'] = nil unless exists(item['logo'])
      end
    end if !!ENV['INTERNAL_ASSETS']

    building = JSON.pretty_generate building if params.has_key? :pretty

    render json: building
  end

  def company
    company = Company.find(params[:id]) rescue {}

    company = Hashie::Mash.new JSON[company.to_json(
      :include => [
        {
          :tags => {
            :include => {
              :tag_category => { only: [:name] }
            },
            :only => [:id, :name]
          }
        },
        {
          :images => {
            :only => [:url]
          }
        }
      ]
    )]

    if company.any?
      company.tags.each do |tag|
        tag.tag_category = tag.tag_category.name
      end if company.tags and company.tags.any?

      company.images.map! do |image|
        if !!ENV['INTERNAL_ASSETS']
          imagepath = RemoteImagePath.new image.url
          filepath = imagepath.get_filepath
          previewpath = imagepath.get_previewpath
          path = File.exist?(File.join(Rails.public_path, previewpath)) ?
            previewpath : filepath
          local_path = File.join(Rails.public_path, path)

          if File.exist? local_path
            imagefile = MiniMagick::Image.open local_path
            dims = imagefile.dimensions

            {
              url: path,
              dims: dims
            }
          end
        else
          {
            url: image.url,
            dims: []
          }
        end
      end.compact! if company.images and company.images.any?


      if !!ENV['INTERNAL_ASSETS']
        remove_domain!(company.logo)
        remove_domain!(company.mainpic)

        company.logo = nil unless exists(company.logo)
      end
    end

    company = JSON.pretty_generate(company) if params.has_key? :pretty

    render json: company
  end

  def categories
    category = TagCategory.all rescue {}

    category = JSON[category.to_json(
      :include => [{
        :tags => {
          :only => [:id, :name]
        }
      }]
    )]

    category.map! do |cat|
      cat = Hashie::Mash.new cat
    end

    category = JSON.pretty_generate(category) if params.has_key? :pretty

    render json: category
  end

  def tags
    companies = Tag.find(params[:id]) rescue {}

    companies = JSON[companies.to_json(
      :include => [
        {
          :tag_category => {
            :only => [:name]
          }
        },
        {
          :companies => {
            :only => [:id, :name, :logo]
          }
        }
      ],
      :only => [:id, :name]
    )]

    companies['companies'].each do |company|
      if company['logo']
        company['logo'].gsub! 'http://www.artplay.ru', '.'
        company['logo'] = nil unless exists(company['logo'])
      end
    end if !!ENV['INTERNAL_ASSETS']

    companies = JSON.pretty_generate(companies) if params.has_key? :pretty

    render json: companies
  end


  # Links of pictures to download

  def pictures
    images = Image.all.pluck(:url)
    logos = Company.all.pluck(:logo, :mainpic).flatten.reject(&:blank?)
    pictures = (images + logos).uniq

    if params.has_key? :length
      render text: pictures.length
    else
      render partial: 'pictures', locals: { pictures: pictures }
    end
  end

  private

  def remove_domain url
    if url
      url.gsub('http://www.artplay.ru', '.')
    else
      nil
    end
  end

  def remove_domain! url
    url.gsub!('http://www.artplay.ru', '.') if url
  end

  def exists path
    if path.is_a? String
      File.exists? Rails.root.join('public', Pathname.new(path))
    else
      false
    end
  end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tags_of_categories
    tags = []

    TagCategory.all.each do |category|
      tags << {name: category.name, tags: category.tags.select(:id, :name)}
    end

    tags.to_json
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/adverts/_form.html.slim
= form_for @advert do |f|
  - if @advert.errors.any?
    #error_explanation
      h2 = "#{pluralize(@advert.errors.count, "error")} prohibited this advert from being saved:"
      ul
        - @advert.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :filename
    = f.text_field :filename, :list => "files", :autofocus => true
    datalist id="files"
      - files = Dir.entries Rails.root.join Pathname.new 'public/videos'
      - files.keep_if { |file| file =~ /(?<!_small).mp4$/ }.each do |file|
        option value="#{file}"= file

  .field
    = f.label :company_id
    = f.text_field :company_id, :list => "companies"

    datalist id="companies"
      - Company.all.each do |company|
        option value="#{company.id}"= raw company.name

  .actions = f.submit

app/views/adverts/edit.html.slim
h1 Editing advert

== render 'form'

= link_to 'Show', @advert
'|
= link_to 'Back', adverts_path

app/views/adverts/index.html.slim
h1 Listing adverts

p#notice = notice

table
  thead
    tr
      th Filename
      th Company
      th
      th
      th

  tbody
    - @adverts.each do |advert|
      tr
        td = advert.filename
        td = (advert.company or {})[:name]
        td = link_to 'Show', advert
        td = link_to 'Edit', edit_advert_path(advert)
        td = link_to 'Destroy', advert, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Advert', new_advert_path, :id => "new_advert"

javascript:
  document.getElementById('new_advert').focus()

app/views/adverts/new.html.slim
h1 New advert

== render 'form'

= link_to 'Back', adverts_path

app/views/adverts/show.html.slim
p#notice = notice

p
  strong Filename:
  = @advert.filename
p
  strong Company:
  = @advert.company.name

= link_to 'Edit', edit_advert_path(@advert)
||
= link_to 'Back', adverts_path

app/views/layouts/adverts.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Adverts</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= javascript_include_tag 'adverts' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArtplayRails</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <script>
    var categories = <%= raw tags_of_categories() %>;
    var adverts = <%= raw Advert.all.as_json.to_json %>;
  </script>
</head>
<body>

<%= yield %>

<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/main/_pictures.slim
= pictures.join "\n"

app/views/main/index.slim
/ .map= inline_svg 'Map.svg', id: "Map", size: '950px*548px', nocomment: true

/ sizes = []

/- 15.times do |index|
  - ratio = (rand * 0.5) + 1.3
  - sizes << {thumb: 85*ratio, preview: 300*ratio}

/.layout
  aside.layout__sidebar
  main.layout__body
    header.layout__header
      nav.navigation
        a href="#"
          span Поиск по услугам
        a.active href="#"
          span Поиск по ARTPLAY
        a href="#"
          span Интерактивная карта
    section.layout__content
      .map
      /.searchbar data-prevent-close='true'
        input.searchbar__input type="text" role='searchbar_input'/
        .searchbar__keyboard role='searchbar_keyboard'
      /.gallery
        .gallery__preview.swiper-container role='gallery_preview'
          .swiper-wrapper
            - sizes.each do |size|
              - width = size[:preview].floor
              .swiper-slide
                img src="http://placehold.it/#{width}x300" width=width height="300"/
        .gallery__thumbs.swiper-container role='gallery_thumb'
          .swiper-wrapper
            - sizes.each do |size|
              - width = size[:thumb].floor
              .swiper-slide
                img src="http://placehold.it/#{width}x85" width=width height="85"/

    footer.layout__footer
      nav.navigation._footer
        a href="#"
          span О проекте
        a href="#"
          span Реклама
        a href="#"
          span Контакты